<a href="https://colab.research.google.com/github/Emrahnyc/Project_two/blob/main/Project_two.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report, balanced_accuracy_score, roc_auc_score
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler


We uploaded the data here

In [30]:
  from google.colab import files
  uploaded = files.upload()


Saving diabetes_data.csv to diabetes_data (1).csv


In [31]:
file=pd.read_csv('diabetes_data.csv')

In [32]:
df=pd.DataFrame(file)

In [33]:
df.head()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1              0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2              0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3              0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4              0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      5.0      18.0      15.0       1.0  0.0   9.0        4.0   
1          1.0      3.0       0.0       0.0       0.0  0.0   7.0        6.0   
2          1.0      5.0      30.0      30.0       1.0  0.0   9.0        4.0   
3          0.0      2.0       0.0       0.0       0.0  0.0  11.0        3.0   
4          0.0      2.0       3.0       0.0       0.0  0.0  11.0        5.0   

   Income  
0     3.0  
1     1.0  
2     8.0  
3     6.0  
4     4.0  

[5 rows x 22 columns]

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Diabetes_binary       253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   HeartDiseaseorAttack  253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  

In [35]:
df["Diabetes_binary"].value_counts()

Diabetes_binary
0.0    218334
1.0     35346
Name: count, dtype: int64

In [61]:
random_undersampler=RandomUnderSampler()
X_under, y_under=random_undersampler.fit_resample(X,y)

In [62]:
y_under.value_counts()

Diabetes_binary
0.0    35346
1.0    35346
Name: count, dtype: int64

In [39]:
# Import RandomOverSampler from imblearn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the RandomOverSampler instance
random_oversampler = RandomOverSampler(random_state=1)

# Fit the data to the model
X_resampled, y_resampled = random_oversampler.fit_resample(X, y)

The result is unbalanced therefore is necessary to move on with an  underfitting or overfitting strategy . In this case is overfitting .

Giving X and y values and splitting train and test with resampled data .

In [40]:
X=df.drop(columns='Diabetes_binary',axis=1)
y=df['Diabetes_binary']

In [41]:
X_resampled_test,X_resampled_train,y_resampled_test,y_resampled_train=train_test_split(X_resampled,y_resampled,random_state=42, test_size=0.2)

In [42]:
scaler=StandardScaler()

In [43]:
X_resampled_train_scaled=scaler.fit_transform(X_resampled_train)
X_resampled_test_scaled=scaler.transform(X_resampled_test)

Logistic Regression Model:

In [44]:
lr_model=LogisticRegression()


In [45]:
lr_model.fit(X_resampled_train_scaled, y_resampled_train)

LogisticRegression()

In [46]:
y_train_predlr=lr_model.predict(X_resampled_train_scaled)
y_test_predlr=lr_model.predict(X_resampled_test_scaled)

In [47]:
train_acc_score_lr=accuracy_score(y_resampled_train,y_train_predlr)
test_score_lr=accuracy_score(y_resampled_test,y_test_predlr)

In [48]:
print(f" Logistic Regression Training Data Score: {train_acc_score_lr}")
print(f"Logistic Regression Testing Data Score: {test_score_lr}")

 Logistic Regression Training Data Score: 0.7476698651155335
Logistic Regression Testing Data Score: 0.7452409441966714


KNN Model:

In [ ]:
# Note: We use only odd numbers because we don't want any ties.
train_scores = []
test_scores = []
for k in range(1, 20, 2):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_resampled_train_scaled, y_resampled_train)
    train_score = knn.score(X_resampled_train_scaled, y_resampled_train)
    test_score= knn.score(X_resampled_test_scaled, y_resampled_test)
    train_scores.append(train_score)
    test_scores.append(test_score)
    print(f"k: {k}, Train/Test Score: {train_score:.3f}/{test_score:.3f}")

# Plot the results
plt.plot(range(1, 20, 2), train_scores, marker='o', label="training scores")
plt.plot(range(1, 20, 2), test_scores, marker="x", label="testing scores")
plt.xlabel("k neighbors")
plt.ylabel("accuracy score")
plt.legend()
plt.show()

k: 1, Train/Test Score: 0.994/0.803


KeyboardInterrupt: 

In [49]:
knn_model=KNeighborsClassifier(n_neighbors=9)

In [50]:
knn_model.fit(X_resampled_train_scaled, y_resampled_train)

KNeighborsClassifier(n_neighbors=9)

In [51]:
y_train_predknn=knn_model.predict(X_resampled_train_scaled)
y_test_predknn=knn_model.predict(X_resampled_test_scaled)

In [52]:
train_acc_score_knn=accuracy_score(y_resampled_train,y_train_predknn)
test_score_knn=accuracy_score(y_resampled_test,y_test_predknn)

In [53]:
print(f"KNN Training Data Score: {train_acc_score_knn}")
print(f"KNN Testing Data Score: {test_score_knn}")

KNN Training Data Score: 0.7911008312913642
KNN Testing Data Score: 0.7420348434449553


In [55]:
print(f" KNN Training Data Score: {knn_model.score(X_resampled_train_scaled, y_resampled_train)}")
print(f"KNN Testing Data Score: {knn_model.score(X_resampled_test, y_resampled_test)}")

 KNN Training Data Score: 0.7911008312913642


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


KNN Testing Data Score: 0.5115133368066092


Random Forrest Model:


In [56]:
rf_model= RandomForestClassifier(n_estimators=500)

In [57]:
rf_model.fit(X_resampled_train_scaled, y_resampled_train)

RandomForestClassifier(n_estimators=500)

In [58]:
y_train_pred_rf=rf_model.predict(X_resampled_train_scaled)
y_test_pred_rf=rf_model.predict(X_resampled_test_scaled)

In [59]:
train_acc_score_rf=accuracy_score(y_resampled_train,y_train_pred_rf)
test_score_rf=accuracy_score(y_resampled_test,y_test_pred_rf)

In [60]:
print(f"Random Forrest Model Training Data Score: {train_acc_score_rf}")
print(f"Random Forrest Model Testing Data Score: {test_score_rf}")

Random Forrest Model Training Data Score: 0.9952481278768864
Random Forrest Model Testing Data Score: 0.837748401243509


In [ ]:
print(f"Training Data Score: {rf_model.score(X_resampled_train_scaled, y_resampled_train)}")
print(f"Testing Data Score: {rf_model.score(X_resampled_test, y_resampled_test)}")

SVC Model:

In [ ]:
svc_model=SVC(kernel="linear")

In [ ]:
svc_model.fit(X_resampled_train_scaled, y_resampled_train)

In [ ]:
y_train_pred_svc=svc_model.predict(X_resampled_train_scaled)
y_test_pred_svc=svc_model.predict(X_resampled_test_scaled)

In [ ]:
train_acc_score_svc=accuracy_score(y_resampled_train,y_train_pred_svc)
test_score_svc=accuracy_score(y_resampled_test,y_test_pred_svc)

In [ ]:
print(f"SVC Training Data Score: {train_acc_score_svc}")
print(f"SVC Testing Data Score: {test_score_svc}")

Classification Report:

In [ ]:
classifier=LogisticRegression()


In [ ]:
classifier.fit(X_resampled, y_resampled)

In [ ]:
classifier_score=classifier.score(X_resampled, y_resampled)

In [ ]:
classifier_pred=classifier.predict(X_resampled)

In [ ]:
print(confusion_matrix(y_resampled, classifier_pred, labels = [1,0]))

In [ ]:
print(classification_report(y_resampled, classifier_pred, labels = [1, 0]))

In [63]:
def process_data(df):
    X = df.drop(['Diabetes_binary'], axis=1)
    y = df['Diabetes_binary']
    X_train, X_test, y_train, y_test = train_test_split(X, y)
    return X_train, X_test, y_train, y_test

In [64]:
def over_sampling (X, y):
  random_oversampler = RandomOverSampler()
  X_over, y_over = random_oversampler.fit_resample(X, y)
  return X_over, y_over


In [65]:
def under_sampling (X, y):
  random_undersampler = RandomUnderSampler()
  X_under, y_under = random_undersampler.fit_resample(X, y)
  return X_under, y_under

In [66]:
def pipe (X, y, model):
    X_train, X_test, y_train, y_test = process_data(df)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_pred_train = model.predict(X_train)
    train_acc_score=accuracy_score(y_train,y_pred_train)
    test_acc_score=accuracy_score(y_test,y_pred)
    print("Accuracy Score:")
    print(accuracy_score(y_test, y_pred))
    print(f"Test Accuracy Score: {test_acc_score}")
    print(f"Train Accuracy Score:{train_acc_score}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("Classification Report:")
    print(classification_report(y_test, y_pred))
    print("Balanced Acc. Score:")
    print(balanced_accuracy_score(y_test, y_pred))

In [67]:
X_under,y_under=under_sampling(X,y)
X_over,y_over=over_sampling(X,y)


In [68]:
y_over.value_counts()


Diabetes_binary
0.0    218334
1.0    218334
Name: count, dtype: int64

In [69]:

y_under.value_counts()

Diabetes_binary
0.0    35346
1.0    35346
Name: count, dtype: int64

In [70]:
pipe(X, y, RandomForestClassifier(n_estimators=100))

Accuracy Score:
0.8596499526963103
Test Accuracy Score: 0.8596499526963103
Train Accuracy Score:0.994654683065279
Confusion Matrix:
[[53001  1592]
 [ 7309  1518]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.88      0.97      0.92     54593
         1.0       0.49      0.17      0.25      8827

    accuracy                           0.86     63420
   macro avg       0.68      0.57      0.59     63420
weighted avg       0.82      0.86      0.83     63420

Balanced Acc. Score:
0.5714055548801743


In [71]:
pipe(X_over, y_over, RandomForestClassifier(n_estimators=100))

Accuracy Score:
0.8604225796278776
Test Accuracy Score: 0.8604225796278776
Train Accuracy Score:0.994502260065174
Confusion Matrix:
[[53097  1545]
 [ 7307  1471]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.88      0.97      0.92     54642
         1.0       0.49      0.17      0.25      8778

    accuracy                           0.86     63420
   macro avg       0.68      0.57      0.59     63420
weighted avg       0.82      0.86      0.83     63420

Balanced Acc. Score:
0.5696515413332437


In [72]:
pipe(X_under, y_under, RandomForestClassifier(n_estimators=100))

Accuracy Score:
0.8612582781456953
Test Accuracy Score: 0.8612582781456953
Train Accuracy Score:0.9946073793755913
Confusion Matrix:
[[53057  1515]
 [ 7284  1564]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.88      0.97      0.92     54572
         1.0       0.51      0.18      0.26      8848

    accuracy                           0.86     63420
   macro avg       0.69      0.57      0.59     63420
weighted avg       0.83      0.86      0.83     63420

Balanced Acc. Score:
0.5745008104494631


In [73]:
pipe(X, y, DecisionTreeClassifier())

Accuracy Score:
0.7950173446862189
Test Accuracy Score: 0.7950173446862189
Train Accuracy Score:0.9946704509618417
Confusion Matrix:
[[47611  6922]
 [ 6078  2809]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.87      0.88     54533
         1.0       0.29      0.32      0.30      8887

    accuracy                           0.80     63420
   macro avg       0.59      0.59      0.59     63420
weighted avg       0.80      0.80      0.80     63420

Balanced Acc. Score:
0.5945736753585104


In [74]:
pipe(X_over, y_over, DecisionTreeClassifier())


Accuracy Score:
0.7984547461368653
Test Accuracy Score: 0.7984547461368653
Train Accuracy Score:0.9944286765478818
Confusion Matrix:
[[47708  6912]
 [ 5870  2930]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.87      0.88     54620
         1.0       0.30      0.33      0.31      8800

    accuracy                           0.80     63420
   macro avg       0.59      0.60      0.60     63420
weighted avg       0.81      0.80      0.80     63420

Balanced Acc. Score:
0.6032037465463866


In [75]:
pipe(X_under, y_under, DecisionTreeClassifier())

Accuracy Score:
0.7982497634815515
Test Accuracy Score: 0.7982497634815515
Train Accuracy Score:0.9946073793755913
Confusion Matrix:
[[47720  6820]
 [ 5975  2905]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.87      0.88     54540
         1.0       0.30      0.33      0.31      8880

    accuracy                           0.80     63420
   macro avg       0.59      0.60      0.60     63420
weighted avg       0.81      0.80      0.80     63420

Balanced Acc. Score:
0.6010469008612573


In [76]:
pipe(X, y, KNeighborsClassifier(n_neighbors=9))

Accuracy Score:
0.8528539892778303
Test Accuracy Score: 0.8528539892778303
Train Accuracy Score:0.8761799642594345
Confusion Matrix:
[[52701  1727]
 [ 7605  1387]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.87      0.97      0.92     54428
         1.0       0.45      0.15      0.23      8992

    accuracy                           0.85     63420
   macro avg       0.66      0.56      0.57     63420
weighted avg       0.81      0.85      0.82     63420

Balanced Acc. Score:
0.5612591143623219
